config/routes.rb
Othello::Application.routes.draw do
  match 'games/new(/:id)' => 'games#new', :as => :new_game
  match 'games/new/auto(/:id)' => 'games#auto', :as => :new_auto_game
  match 'games/:id/undo' => 'games#undo', :as => :undo_play
  match 'games/:id/:move_id' => 'games#play', :as => :play_game
  match 'games/:id' => 'games#show', :as => :show_game
  match 'games' => 'games#new'

  

  root :to => 'games#new'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :turn, :auto_opponent
  
  DIRECTIONS = [[-1,0],[1,0],[0,1],[0,-1],[-1,-1],[-1,1],[1,-1],[1,1]]
  
  has_many :tiles, :dependent => :destroy
  has_many :plays, :dependent => :destroy
  
  after_create :initialize_game
  def initialize_game
    # Sets up the board.
    # I admit this isn't the most efficient way to go about this.  I could, for example, create a tile whenever there's a move.
    # I did it this way because it seemed easier to figure out possible moves.
    
    (0...8).each do |row|
      (0...8).each do |col|
        if ((row == 3 && col == 3) || (row == 4 && col == 4))
          tiles << Tile.create(:game_id => self.id, :row => row, :col => col, :value => false)
        elsif ((row == 3 && col == 4) || (row == 4 && col == 3))
          tiles << Tile.create(:game_id => self.id, :row => row, :col => col, :value => true)
        else
          tiles << Tile.create(:game_id => self.id, :row => row, :col => col)
        end
      end
    end
  end
  
  def black_count
    all_positions_for(false).count
  end
  
  def white_count
    all_positions_for(true).count
  end
  
  def change_turn
    update_attribute(:turn, !turn)
  end
  
  def opp(value)
    turn? ? false : true
  end
  
  def all_positions_for(value)
    tiles.select{|tile| (value == true ? tile.is_white? : tile.is_black?) }
  end
  
  def tile_at(pos, dir)
    # both position and direction need to be 1-dim arrays with 2 elements, (x, y) coords
    x, y = pos.first + dir.first, pos.last + dir.last
    (0 <= x && x < 8 && 0 <= y && y < 8) ? tiles[x*8+y] : nil
  end
  
  def moves
    moves_for(turn)
  end
  
  def moves_for(value)
    # Determines possible moves for a player.
    # For each direction, it checks for at least one possible opposite value (a flip) and a tail value (same as the player).
    
    moves = []
    all_positions_for(value).each do |pos|
      DIRECTIONS.each do |dir|
        flips = []
        tested_tile = tile_at([pos.row, pos.col], dir)
         
        while !tested_tile.nil? && tested_tile.value == opp(value)
          flips << tested_tile
          tested_tile = tile_at([tested_tile.row, tested_tile.col], dir)
        end
        
        if flips.any? && !tested_tile.nil? && tested_tile.value.nil?
          ind = moves.index{ |el| el[:move] == tested_tile }
          if ind.nil?
            moves << { :move => tested_tile, :flips => flips, :corner => tested_tile.is_corner? }
          else
            moves[ind][:flips] = (moves[ind][:flips] + flips).uniq
          end
        end 
      end
    end
    
    return moves
  end
  
  def undo_last_play
    # If you undo, all flips and the tail value need to be switched back.
    change_turn #back
    play_to_undo = plays.last
    play_to_undo.tiles.each { |mid_tile| mid_tile.flip(nil) }
    play_to_undo.tile.set_value(nil)
    play_to_undo.delete
  end
  
  def undos_allowed?
    !auto_opponent? && plays.any?
  end
  
  def auto_opponent_needs_to_play?(moves)
    auto_opponent? && turn? && moves.any?
  end
  
  def auto_play(moves)
    # This issues an opponent's play if you were playing the computer.
    # If there's a tail in a corner, it goes for that move.  Otherwise, the move is whichever has the maximum number of flips.
    # This isn't super efficient either; I just wanted to get something running quickly.
    
    prev_tiles = tiles.map { |tile| {:row => tile.row, :col => tile.col, :value => tile.value} }
    
    move_index_with_max_flips = 0
    move_index_of_last_corner = nil
    max_flips = 0
    
    moves.each_index do |move_index|
      ct = moves[move_index][:flips].count
      if ct >= max_flips
        max_flips = ct
        move_index_with_max_flips = move_index
      end
      
      move_index_of_last_corner = move_index if moves[move_index][:corner]
    end
  
    move = move_index_of_last_corner.nil? ? moves[move_index_with_max_flips][:move] : moves[move_index_of_last_corner][:move]
    
    play = Play.create(:game_id => self.id, :tile_id => move.id, :value => turn)
    moves[move_index_with_max_flips][:flips].each { |mid_tile| mid_tile.flip play }
    move.set_value(turn)
    change_turn
    
    return prev_tiles
  end
end

app/models/play.rb
class Play < ActiveRecord::Base
  attr_accessible :game_id, :value, :tile_id
  belongs_to :game
  belongs_to :tile
  has_many :tiles
  
  
  def flip_flips
    flip_list.each { |tile_id| Tile.find(tile_id).flip }
  end
end

app/models/tile.rb
class Tile < ActiveRecord::Base
  attr_accessible :col, :game_id, :row, :value, :play_id
  belongs_to :game
  belongs_to :play
  has_many :plays
  
  def is_white?
    value?
  end
  
  def is_black?
    value == false
  end
  
  def flip(play)
    flip_to = is_white? ? false : true
    update_attributes(:value => flip_to, :play_id => (play.nil? ? nil : play.id))
  end
  
  def is_available?(moves)
    # returns the number of flips
    m = moves.select{ |el| el[:move] == self }
    m.any? ? m.first[:flips].count : 0
  end
  
  def set_value(new_value)
    update_attribute(:value, new_value)
  end
  
  def is_corner?
    [0,8].include?(row) && [0,8].include?(col)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET games/:id/undo
  def undo
    @game = Game.find(params[:id])
    @game.undo_last_play
    
    respond_to do |format|
      format.html { redirect_to show_game_path(@game) }
      format.json { render :json => @game }
    end
  end
  
  # GET /games/:id/:player/:move_id
  # GET /games/:id/:player/:move_id.json
  def play
    @game = Game.find(params[:id])
    @moves = @game.moves
    
    tile = Tile.find(params[:move_id])
    move = @moves.select{ |el| el[:move] == tile }
    if move.any?
      play = Play.create(:game_id => @game.id, :tile_id => tile.id, :value => @game.turn)
      move.first[:flips].each { |mid_tile| mid_tile.flip play }
      tile.set_value(@game.turn)
      @game.change_turn
    end
    
    respond_to do |format|
      format.html { redirect_to show_game_path(@game) }
      format.json { render :json => @game }
    end
  end
  
  # GET /games/1
  # GET /games/1.json
  def show
    respond_to do |format|
      games = Game.where(:id => params[:id])
      @outcome = nil
      
      if games.any?
        @game = games.first
    
        @moves = @game.moves
        @game_before_auto_play_tiles = []
    
        if @game.auto_opponent_needs_to_play?(@moves)
          @game_before_auto_play_tiles = @game.auto_play(@moves)
          @moves = @game.moves
        end
    
        unless @moves.any?
          b = @game.black_count
          w = @game.white_count
          @outcome = b > w ? 'black' : (b == w ? 'draw' : 'white')
        end
    
        format.html # show.html.erb
        format.json { render :json => @game }
      else
        format.html { redirect_to new_game_path }
      end
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    if defined?(params[:id])  && !params[:id].nil?
      game = Game.find(params[:id])
      game.destroy
    end
    @game = Game.create(:auto_opponent => false)
    
    respond_to do |format|
      format.html { redirect_to show_game_path(@game) }
      format.json { render :json => @game, :status => :created, :location => @game }
    end
  end
  
  # GET /games/new/auto
  # GET /games/new.json
  def auto
    if defined?(params[:id])  && !params[:id].nil?
      game = Game.find(params[:id])
      game.destroy
    end
    @game = Game.create
    
    respond_to do |format|
      format.html { redirect_to show_game_path(@game) }
      format.json { render :json => @game, :status => :created, :location => @game }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.haml
.games
  - @games.each do |game|
    .outcome= game.outcome_display
    .lnk= game.playable? ? link_to('play', game) : link_to('view', game)
    .lnk= link_to 'delete', game, :method => :delete, :data => { :confirm => 'you sure?' }

%br

= link_to 'new game?', new_game_path

app/views/games/show.html.haml
.othelloh

- if @game_before_auto_play_tiles.any?
  .prev.board
    - @game_before_auto_play_tiles.each do |frozen_tile|
      - cls = frozen_tile[:value].nil? ? '' : (frozen_tile[:value] ? 'white' : 'black')
      .tile{ :row=> frozen_tile[:row], :col=> frozen_tile[:col], :class => cls }

.current.board
  - @game.tiles.each do |tile|
    - cls = tile.is_black? ? 'black' : (tile.is_white? ? 'white' : '')
    - if cls == ''
      - ct = tile.is_available? @moves
      - if ct > 0
        = link_to play_game_path(@game, tile) do
          .tile.available{ :row=> tile.row, :col=> tile.col }
            / %span.count= ct
      - else
        .tile{ :row=> tile.row, :col=> tile.col }
    - elsif @game.undos_allowed? && @game.plays.last.tile == tile
      = link_to(undo_play_path(@game), :class => 'undo') do
        .tile{ :row=> tile.row, :col=> tile.col, :class => cls }
          %span undo
    - else
      .tile{ :row=> tile.row, :col=> tile.col, :class => cls }

.info
  .scores
    - if @outcome.nil?
      - cls = @game.turn == false ? 'turn' : ''
      .black.score_board{:class => cls}
        - cls = @game.black_count < 10 ? 'single' : 'double'
        %span.count{:class => cls}= @game.black_count
        
      - cls = @game.turn ? 'turn' : ''
      .white.score_board{:class => cls}
        - cls = @game.white_count < 10 ? 'single' : 'double'
        %span.count{:class => cls}= @game.white_count
    - else
      .winner{:class => @outcome}
      
      .black.score_board
        - cls = @game.black_count < 10 ? 'single' : 'double'
        %span.count{:class => cls}= @game.black_count
      .white.score_board
        - cls = @game.white_count < 10 ? 'single' : 'double'
        %span.count{:class => cls}= @game.white_count
.new
  = link_to new_auto_game_path(@game) do
    .one.player 1
  = link_to new_game_path(@game) do
    .two.player 2

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Othello</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Peralta' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <%= yield %>
  </div>
</body>
</html>